export enum NotificationType {
  TODO_PENDING_APPROVAL = 'TODO_PENDING_APPROVAL',
  TODO_APPROVED = 'TODO_APPROVED',
  TODO_AUTO_APPROVED = 'TODO_AUTO_APPROVED',
  TODO_REJECTED = 'TODO_REJECTED',
  DELEGATION_CREATED = 'DELEGATION_CREATED',
  DELEGATION_REVOKED = 'DELEGATION_REVOKED',
}
