export enum TodoStatus {
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  PENDING_OVERTIME_APPROVAL = 'PENDING_OVERTIME_APPROVAL',
  APPROVED = 'APPROVED',
  AUTO_APPROVED = 'AUTO_APPROVED',
  REJECTED = 'REJECTED',
  ONGOING = 'ONGOING',
  PAUSED = 'PAUSED',
  DONE = 'DONE',
  DEFERRED = 'DEFERRED',
}
